### PR TITLE
Add new models

### PR DESCRIPTION
**Pull request by BLKSerene**
This PR adds [4 new models](https://github.com/lancopku/pkuseg-python/releases/tag/v0.0.25) (optimized default / art / entertainment / science) published by authors of `pkuseg` to be downloaded and used by users.

It seems that the authors of the [original repo](https://github.com/lancopku/pkuseg-python/pulls) have not replied to issues or pull requests for some time, so I decided to send the PR here.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Hi, thanks for the PR! Is there any more information about these releases, or do you know anything about why they weren't added to a `pkuseg` release as downloads?

**Comment by BLKSerene** [comment]
These models are published in [releases](https://github.com/lancopku/pkuseg-python/releases/tag/v0.0.25) of the original repo only, but the configuration file for downloads are not updated accordingly. I'm not sure about the reason, and the authors seem to not have time to reply to questions or issues. Perhaps they are simply too busy working on other projects.

**Comment by adrianeboyd** [comment]
You should be able to load it directly from a path without any hacking/renaming:

```python
nlp = spacy.blank(
    "zh",
    config={
        "nlp": {"tokenizer": {"segmenter": "pkuseg"}},
        "initialize": {"tokenizer": {"pkuseg_model": "/tmp/science"}},
    },
)
# reads in tokenizer data from path
nlp.initialize()
```

where I've unpacked `science.zip` into `/tmp/science`. It will show a warning, but it can still read the `.pkl` format as a fallback.

From this point on the model is saved with the spacy pipeline (with `nlp.to_disk`) so you don't need the path anymore.

**Comment by BLKSerene** [comment]
@adrianeboyd Great!

**Comment by adrianeboyd** [comment]
So I don't really think these links need to be added? But if they're added to `pkuseg` we can add them, too.

**Comment by BLKSerene** [comment]
@adrianeboyd 🆗

**Pull request closed without merging**
